### ISSUE TITLE
Hi, I'm confused about the calculate of pi(k) in Eq. 4

### ISSUE THREAD

**Issue by SSDUT-Caiyq** [CVMI-Lab/SimGCD#10]
If the prototype is a simple linear layer, how can the procedure for computing the exponent (exp(1/\tao_s ...) /  \sum k' exp(...) ) in Equation 4 be implemented?

**Comment by xwen99** [comment]
Actually, we do not recommend using linear layers, which could easily overfit to Old classes and find it hard to discover novel ones.
