### ISSUE TITLE
About entropy regularization term

### ISSUE THREAD

**Issue by hjs2027864933** [CVMI-Lab/SimGCD#3]
Thanks for your excellent work, but I have a doubt about entropy regularization. The code in your repo subtracts the entropy regularization term, but in the paper it adds the entropy regularization term. Is it a tiny clerical error in the paper?

https://github.com/CVMI-Lab/SimGCD/blob/1765452663e7c52e7f0bd0759543655d85524b94/model/simgcd.py#L111-L112

![issue](https://user-images.githubusercontent.com/49865152/218298179-daf0e067-0a8e-417b-af4f-6436f31b25a3.png)

**Comment by xwen99** [comment]
Hi @hjs2027864933, thanks for pointing this out. The code is correct, and we will update the paper in the next version.

**Comment by hjs2027864933** [comment]
> Hi @hjs2027864933, thanks for pointing this out. The code is correct, and we will update the paper in the next version.

thank you for your reply.
