### ISSUE TITLE
About p, q', and p'

### ISSUE THREAD

**Issue by Fulin-Gao** [CVMI-Lab/SimGCD#6]
For soft pseudo-label $\pmb p$, $\pmb p^{\prime}$, $\pmb q^{\prime}$, we are a little confused, what is the difference between them?

**Comment by xwen99** [comment]
Hi @Fulin-Gao, $\boldsymbol{p}$ stands for predictions of the student model, and $\boldsymbol{q}$ means those from the teacher model. The one without prime symbol $\prime$ means output from the 1st augmented view, and the one with prime means output from another view. This set of symbols follows self-distillation and self-supervised learning literature.
