### ISSUE TITLE
Eq. (3) about categories k

### ISSUE THREAD

**Issue by Cliffia123** [CVMI-Lab/SimGCD#7]
How do we know the number of categories k, k is the set of y_l and y_u, but in an actual open-set scenario, we don't know the number of y_u, i.e. how many unknown categories there are in a scene. If k is the number of all categories, isn't that smart?

**Comment by xwen99** [comment]
Hi @Cliffia123,

Thanks for reaching out! Your concern regarding the category number is important and practical.
As stated in the first paragraph on page 8, "We assume the number of categories is known a-priori following prior works". But dropping this prior is indeed a practical direction. Thus in sec. B2 (appendix), we explored the results of adopting an off-the-shelf estimation of $K$ from Vaze et al., or just simply using a relatively big empirical estimation (e.g., $2K$). We found that our method is actually quite robust to a wide range of $K$ estimations (also supported by Fig.11 in the main paper).
This is indeed a valuable research direction, and we also suggest you take a look at another paper, [GPC](https://arxiv.org/abs/2305.06144), from our team, in which $K$ estimation is incorporated into the learning process.

Best,

Xin Wen

**Comment by Cliffia123** [comment]
> Hi @Cliffia123,
> 
> Thanks for reaching out! Your concern regarding the category number is important and practical. As stated in the first paragraph on page 8, "We assume the number of categories is known a-priori following prior works". But dropping this prior is indeed a practical direction. Thus in sec. B2 (appendix), we explored the results of adopting an off-the-shelf estimation of K from Vaze et al., or just simply using a relatively big empirical estimation (e.g., 2K). We found that our method is actually quite robust to a wide range of K estimations (also supported by Fig.11 in the main paper). This is indeed a valuable research direction, and we also suggest you take a look at another paper, [GPC](https://arxiv.org/abs/2305.06144), from our team, in which K estimation is incorporated into the learning process.
> 
> Best,
> 
> Xin Wen

Thank you for your response, I should have reviewed the appendix beforehand. I have another question: Is "off-the-shelf" referring to semi-supervised k-means clustering? If it is, I would like to confirm whether the variation in SimGCD(w/Est) in Table 8 and Table 9 (under the assumption of unknown categories) is related to the generation of representation tokens and joint representations through post-backbone learning in SimGCD(w/Est).

**Comment by Cliffia123** [comment]
> Hi @Cliffia123,
> 
> Thanks for reaching out! Your concern regarding the category number is important and practical. As stated in the first paragraph on page 8, "We assume the number of categories is known a-priori following prior works". But dropping this prior is indeed a practical direction. Thus in sec. B2 (appendix), we explored the results of adopting an off-the-shelf estimation of K from Vaze et al., or just simply using a relatively big empirical estimation (e.g., 2K). We found that our method is actually quite robust to a wide range of K estimations (also supported by Fig.11 in the main paper). This is indeed a valuable research direction, and we also suggest you take a look at another paper, [GPC](https://arxiv.org/abs/2305.06144), from our team, in which K estimation is incorporated into the learning process.
> 
> Best,
> 
> Xin Wen

@xwen99 Thank you for your response, I should have reviewed the appendix beforehand. I have another question: Is "off-the-shelf" referring to semi-supervised k-means clustering? If it is, I would like to confirm whether the variation in SimGCD(w/Est) in Table 8 and Table 9 (under the assumption of unknown categories) is related to the generation of representation tokens and joint representations through post-backbone learning in SimGCD(w/Est).

**Comment by xwen99** [comment]
Hi @Cliffia123, "off-the-shelf" means directly setting $K$ as those predicted by Vaze et al. The architecture of SimGCD in that table has no difference from the main paper, except that the number of prototypes (dimension of the classification layer) is set to the estimated K rather than the GT K.

**Comment by Cliffia123** [comment]
> Hi @Cliffia123, "off-the-shelf" means directly setting K as those predicted by Vaze et al. The architecture of SimGCD in that table has no difference from the main paper, except that the number of prototypes (dimension of the classification layer) is set to the estimated K rather than the GT K.

@xwen99 I get it, thank you so much :)
