### ISSUE TITLE
Could you release the code for reimplementing UNO and RS?

### ISSUE THREAD

**Issue by ycwang-libra** [CVMI-Lab/SimGCD#9]
As same as your issue 'https://github.com/sgvaze/generalized-category-discovery/issues/20' in work 'GCD', could you please provide the code for implementing UNO and RS for further research?

**Comment by xwen99** [comment]
Hi, we actually did not reimplement RS, and just took the results from GCD. Regarding UNO, the reproduction is quite easy, the major modification is to replace the pseudo-labelling part with sinkhorn (you may find the implementation of this function from UNO or SwAV's official codebase). You may also align other details according to your needs (eg, representation learning). Hope that is helpful.
